<a href="https://colab.research.google.com/github/Alfiaadmy/food-security-ews-jatim/blob/main/notebooks/Preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
import numpy as np
import os

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)

In [ ]:
folder = "/content/drive/MyDrive/0. BISMILLAH TA LULUS 3,5 TAHUN SUMMA CUMLAUDE AMIINN YA ALLAH/DATA/DATA DIPAKAI CLEAN"

os.listdir(folder)

['KONSUMSI_JATIM_2018_2024 - KONSUMSI_JATIM_2018_2024.csv',
 'DATA EKSOGEN 2018-2026.csv',
 'DATA PRODUKSI PADI 2018-2026 .xlsx',
 'DATA KONSUMSI BERAS FINAL WILAYAH JATIM 2025.xlsx',
 'DATA PENDUDUK 2018-2026.xlsx']

# FILE 1 DATA PRODUKSI

In [ ]:
produksi = pd.read_excel(f"{folder}/DATA PRODUKSI PADI 2018-2026 .xlsx")

produksi.head()

    Kabupaten  Tahun  Bulan Produksi Padi
0   Bangkalan   2018      1       4739.48
1  Banyuwangi   2018      1      27729.16
2      Blitar   2018      1       2123.29
3  Bojonegoro   2018      1      26071.89
4   Bondowoso   2018      1       8154.93

In [ ]:
print("Shape :", produksi.shape)

display(produksi.info())

display(produksi.describe(include='all'))

Shape : (4408, 4)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4408 entries, 0 to 4407
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Kabupaten      4408 non-null   object
 1   Tahun          4408 non-null   int64
 2   Bulan          4408 non-null   int64
 3   Produksi Padi  4408 non-null   object
dtypes: int64(2), object(2)
memory usage: 137.9+ KB

None

        Kabupaten        Tahun        Bulan Produksi Padi
count        4408  4408.000000  4408.000000          4408
unique         76          NaN          NaN          4160
top     Bangkalan          NaN          NaN             0
freq          100          NaN          NaN           134
mean          NaN  2022.172414     6.224138           NaN
std           NaN     2.560853     3.494446           NaN
min           NaN  2018.000000     1.000000           NaN
25%           NaN  2020.000000     3.000000           NaN
50%           NaN  2022.000000     6.000000           NaN
75%           NaN  2025.000000     9.000000           NaN
max           NaN  2026.000000    12.000000           NaN

In [ ]:
produksi.isnull().sum()

Kabupaten        0
Tahun            0
Bulan            0
Produksi Padi    0
dtype: int64

In [ ]:
print("Duplicate :", produksi.duplicated().sum())

Duplicate : 0

In [ ]:
sorted(produksi["Kabupaten"].unique())

['BANGKALAN',
 'BANYUWANGI',
 'BLITAR',
 'BOJONEGORO',
 'BONDOWOSO',
 'Bangkalan',
 'Banyuwangi',
 'Blitar',
 'Bojonegoro',
 'Bondowoso',
 'GRESIK',
 'Gresik',
 'JEMBER',
 'JOMBANG',
 'Jember',
 'Jombang',
 'KEDIRI',
 'KOTA BATU',
 'KOTA BLITAR',
 'KOTA KEDIRI',
 'KOTA MADIUN',
 'KOTA MALANG',
 'KOTA MOJOKERTO',
 'KOTA PASURUAN',
 'KOTA PROBOLINGGO',
 'KOTA SURABAYA',
 'Kediri',
 'Kota Batu',
 'Kota Blitar',
 'Kota Kediri',
 'Kota Madiun',
 'Kota Malang',
 'Kota Mojokerto',
 'Kota Pasuruan',
 'Kota Probolinggo',
 'Kota Surabaya',
 'LAMONGAN',
 'LUMAJANG',
 'Lamongan',
 'Lumajang',
 'MADIUN',
 'MAGETAN',
 'MALANG',
 'MOJOKERTO',
 'Madiun',
 'Magetan',
 'Malang',
 'Mojokerto',
 'NGANJUK',
 'NGAWI',
 'Nganjuk',
 'Ngawi',
 'PACITAN',
 'PAMEKASAN',
 'PASURUAN',
 'PONOROGO',
 'PROBOLINGGO',
 'Pacitan',
 'Pamekasan',
 'Pasuruan',
 'Ponorogo',
 'Probolinggo',
 'SAMPANG',
 'SIDOARJO',
 'SITUBONDO',
 'SUMENEP',
 'Sampang',
 'Sidoarjo',
 'Situbondo',
 'Sumenep',
 'TRENGGALEK',
 'TUBAN',
 'TULUNGAGUNG',
 'Trenggalek',
 'Tuban',
 'Tulungagung']

In [ ]:
print("Jumlah Kabupaten/Kota :", produksi["Kabupaten"].nunique())

Jumlah Kabupaten/Kota : 76

In [ ]:
sorted(produksi["Tahun"].unique())

[np.int64(2018),
 np.int64(2019),
 np.int64(2020),
 np.int64(2021),
 np.int64(2022),
 np.int64(2023),
 np.int64(2024),
 np.int64(2025),
 np.int64(2026)]

In [ ]:
sorted(produksi["Bulan"].unique())

[np.int64(1),
 np.int64(2),
 np.int64(3),
 np.int64(4),
 np.int64(5),
 np.int64(6),
 np.int64(7),
 np.int64(8),
 np.int64(9),
 np.int64(10),
 np.int64(11),
 np.int64(12)]

In [ ]:
produksi.groupby("Kabupaten")["Tahun"].nunique().sort_values()

Kabupaten
BANGKALAN           2
BANYUWANGI          2
BLITAR              2
BOJONEGORO          2
BONDOWOSO           2
JOMBANG             2
JEMBER              2
GRESIK              2
KOTA PASURUAN       2
KOTA MOJOKERTO      2
KOTA MALANG         2
KOTA MADIUN         2
KOTA KEDIRI         2
KOTA BLITAR         2
KOTA BATU           2
KEDIRI              2
KOTA PROBOLINGGO    2
KOTA SURABAYA       2
PAMEKASAN           2
PACITAN             2
PASURUAN            2
PONOROGO            2
SIDOARJO            2
PROBOLINGGO         2
SAMPANG             2
NGAWI               2
MALANG              2
MOJOKERTO           2
MADIUN              2
MAGETAN             2
LAMONGAN            2
LUMAJANG            2
NGANJUK             2
TRENGGALEK          2
SUMENEP             2
TULUNGAGUNG         2
TUBAN               2
SITUBONDO           2
Kota Malang         9
Kota Madiun         9
Blitar              9
Banyuwangi          9
Bangkalan           9
Kota Blitar         9
Kota Batu           9
Kediri              9
Kota Kediri         9
Jombang             9
Mojokerto           9
Malang              9
Magetan             9
Madiun              9
Kota Surabaya       9
Kota Probolinggo    9
Lamongan            9
Lumajang            9
Kota Pasuruan       9
Ngawi               9
Nganjuk             9
Bojonegoro          9
Gresik              9
Bondowoso           9
Jember              9
Kota Mojokerto      9
Ponorogo            9
Probolinggo         9
Pamekasan           9
Pasuruan            9
Pacitan             9
Sidoarjo            9
Sumenep             9
Sampang             9
Situbondo           9
Trenggalek          9
Tuban               9
Tulungagung         9
Name: Tahun, dtype: int64

In [ ]:
produksi.groupby("Kabupaten").size().sort_values()

Kabupaten
BANGKALAN            16
BANYUWANGI           16
BLITAR               16
BOJONEGORO           16
BONDOWOSO            16
JOMBANG              16
JEMBER               16
GRESIK               16
KOTA PASURUAN        16
KOTA MOJOKERTO       16
KOTA MALANG          16
KOTA MADIUN          16
KOTA KEDIRI          16
KOTA BLITAR          16
KOTA BATU            16
KEDIRI               16
KOTA PROBOLINGGO     16
KOTA SURABAYA        16
PAMEKASAN            16
PACITAN              16
PASURUAN             16
PONOROGO             16
SIDOARJO             16
PROBOLINGGO          16
SAMPANG              16
NGAWI                16
MALANG               16
MOJOKERTO            16
MADIUN               16
MAGETAN              16
LAMONGAN             16
LUMAJANG             16
NGANJUK              16
TRENGGALEK           16
SUMENEP              16
TULUNGAGUNG          16
TUBAN                16
SITUBONDO            16
Kota Malang         100
Kota Madiun         100
Blitar              100
Banyuwangi          100
Bangkalan           100
Kota Blitar         100
Kota Batu           100
Kediri              100
Kota Kediri         100
Jombang             100
Mojokerto           100
Malang              100
Magetan             100
Madiun              100
Kota Surabaya       100
Kota Probolinggo    100
Lamongan            100
Lumajang            100
Kota Pasuruan       100
Ngawi               100
Nganjuk             100
Bojonegoro          100
Gresik              100
Bondowoso           100
Jember              100
Kota Mojokerto      100
Ponorogo            100
Probolinggo         100
Pamekasan           100
Pasuruan            100
Pacitan             100
Sidoarjo            100
Sumenep             100
Sampang             100
Situbondo           100
Trenggalek          100
Tuban               100
Tulungagung         100
dtype: int64

In [ ]:
cek = produksi.groupby(
    ["Kabupaten","Tahun","Bulan"]
).size().reset_index(name="Jumlah")

cek[cek["Jumlah"]>1]

Empty DataFrame
Columns: [Kabupaten, Tahun, Bulan, Jumlah]
Index: []

In [ ]:
produksi["Kabupaten"] = (
    produksi["Kabupaten"]
    .str.strip()
    .str.title()
)

In [ ]:
print(produksi["Kabupaten"].nunique())

sorted(produksi["Kabupaten"].unique())

38

['Bangkalan',
 'Banyuwangi',
 'Blitar',
 'Bojonegoro',
 'Bondowoso',
 'Gresik',
 'Jember',
 'Jombang',
 'Kediri',
 'Kota Batu',
 'Kota Blitar',
 'Kota Kediri',
 'Kota Madiun',
 'Kota Malang',
 'Kota Mojokerto',
 'Kota Pasuruan',
 'Kota Probolinggo',
 'Kota Surabaya',
 'Lamongan',
 'Lumajang',
 'Madiun',
 'Magetan',
 'Malang',
 'Mojokerto',
 'Nganjuk',
 'Ngawi',
 'Pacitan',
 'Pamekasan',
 'Pasuruan',
 'Ponorogo',
 'Probolinggo',
 'Sampang',
 'Sidoarjo',
 'Situbondo',
 'Sumenep',
 'Trenggalek',
 'Tuban',
 'Tulungagung']

In [ ]:
produksi.groupby("Kabupaten")["Tahun"].nunique()

Kabupaten
Bangkalan           9
Banyuwangi          9
Blitar              9
Bojonegoro          9
Bondowoso           9
Gresik              9
Jember              9
Jombang             9
Kediri              9
Kota Batu           9
Kota Blitar         9
Kota Kediri         9
Kota Madiun         9
Kota Malang         9
Kota Mojokerto      9
Kota Pasuruan       9
Kota Probolinggo    9
Kota Surabaya       9
Lamongan            9
Lumajang            9
Madiun              9
Magetan             9
Malang              9
Mojokerto           9
Nganjuk             9
Ngawi               9
Pacitan             9
Pamekasan           9
Pasuruan            9
Ponorogo            9
Probolinggo         9
Sampang             9
Sidoarjo            9
Situbondo           9
Sumenep             9
Trenggalek          9
Tuban               9
Tulungagung         9
Name: Tahun, dtype: int64

In [ ]:
produksi.groupby("Kabupaten").size()

Kabupaten
Bangkalan           116
Banyuwangi          116
Blitar              116
Bojonegoro          116
Bondowoso           116
Gresik              116
Jember              116
Jombang             116
Kediri              116
Kota Batu           116
Kota Blitar         116
Kota Kediri         116
Kota Madiun         116
Kota Malang         116
Kota Mojokerto      116
Kota Pasuruan       116
Kota Probolinggo    116
Kota Surabaya       116
Lamongan            116
Lumajang            116
Madiun              116
Magetan             116
Malang              116
Mojokerto           116
Nganjuk             116
Ngawi               116
Pacitan             116
Pamekasan           116
Pasuruan            116
Ponorogo            116
Probolinggo         116
Sampang             116
Sidoarjo            116
Situbondo           116
Sumenep             116
Trenggalek          116
Tuban               116
Tulungagung         116
dtype: int64

In [ ]:
produksi[
    (produksi["Tahun"]==2025)
].head(30)

             Kabupaten  Tahun  Bulan Produksi Padi
3192         Bangkalan   2025      1       1699.02
3193        Banyuwangi   2025      1      30376.17
3194            Blitar   2025      1       3165.85
3195        Bojonegoro   2025      1      24345.29
3196         Bondowoso   2025      1      12925.24
3197         Bangkalan   2025      1         1,699
3198        Banyuwangi   2025      1        30,376
3199            Blitar   2025      1         3,166
3200        Bojonegoro   2025      1        24,345
3201         Bondowoso   2025      1        12,925
3202            Gresik   2025      1       1113.24
3203            Gresik   2025      1         1,113
3204            Jember   2025      1       32756.8
3205           Jombang   2025      1      13037.97
3206            Jember   2025      1        32,757
3207           Jombang   2025      1        13,038
3208            Kediri   2025      1       6210.83
3209         Kota Batu   2025      1        835.57
3210       Kota Blitar   2025      1         50.21
3211       Kota Kediri   2025      1        728.88
3212       Kota Madiun   2025      1         889.4
3213       Kota Malang   2025      1        580.82
3214    Kota Mojokerto   2025      1           0.1
3215     Kota Pasuruan   2025      1        279.88
3216  Kota Probolinggo   2025      1        240.53
3217     Kota Surabaya   2025      1           240
3218            Kediri   2025      1         6,211
3219         Kota Batu   2025      1           836
3220       Kota Blitar   2025      1            50
3221       Kota Kediri   2025      1           729

In [ ]:
produksi["Produksi Padi"] = (
    produksi["Produksi Padi"]
    .astype(str)
    .str.replace(",", "", regex=False)   # hilangkan pemisah ribuan
    .replace("-", np.nan)                # "-" menjadi NaN
)

produksi["Produksi Padi"] = pd.to_numeric(
    produksi["Produksi Padi"],
    errors="coerce"
)

In [ ]:
produksi.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4408 entries, 0 to 4407
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Kabupaten      4408 non-null   object
 1   Tahun          4408 non-null   int64
 2   Bulan          4408 non-null   int64
 3   Produksi Padi  4340 non-null   float64
dtypes: float64(1), int64(2), object(1)
memory usage: 137.9+ KB

In [ ]:
produksi[
    (produksi.Kabupaten=="Bangkalan") &
    (produksi.Tahun==2025)
].sort_values("Bulan")

      Kabupaten  Tahun  Bulan  Produksi Padi
3192  Bangkalan   2025      1        1699.02
3197  Bangkalan   2025      1        1699.00
3268  Bangkalan   2025      2       21909.75
3273  Bangkalan   2025      2       21910.00
3344  Bangkalan   2025      3       84963.49
3349  Bangkalan   2025      3       84963.00
3420  Bangkalan   2025      4       32136.93
3425  Bangkalan   2025      4       32137.00
3496  Bangkalan   2025      5        2446.54
3501  Bangkalan   2025      5        2447.00
3572  Bangkalan   2025      6       26182.19
3577  Bangkalan   2025      6       26182.00
3648  Bangkalan   2025      7       35418.58
3653  Bangkalan   2025      7       35419.00
3724  Bangkalan   2025      8       16360.09
3729  Bangkalan   2025      8       16360.00
3800  Bangkalan   2025      9         849.69
3805  Bangkalan   2025      9         850.00
3876  Bangkalan   2025     10         973.01
3881  Bangkalan   2025     10         973.00
3952  Bangkalan   2025     11           0.00
3957  Bangkalan   2025     11            NaN
4028  Bangkalan   2025     12         849.52
4033  Bangkalan   2025     12         850.00

In [ ]:
produksi = produksi.reset_index(drop=True)

In [ ]:
produksi.groupby(
    ["Kabupaten","Tahun","Bulan"]
).size().value_counts()

1    3192
2     608
Name: count, dtype: int64